# Generated by Django 2.2.3 on 2019-07-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app1',
            name='name',
            field=models.CharField(default='Безымянная', max_length=255),
            preserve_default=False,
        ),
    ]
